# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video = QtWidgets.QLabel(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(380, 10, 591, 331))
        self.video.setFrameShape(QtWidgets.QFrame.Box)
        self.video.setText("")
        self.video.setObjectName("video")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 70, 231, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_input = QtWidgets.QPushButton(self.frame)
        self.btn_input.setGeometry(QtCore.QRect(70, 60, 91, 41))
        self.btn_input.setObjectName("btn_input")
        self.btn_start_stop = QtWidgets.QPushButton(self.frame)
        self.btn_start_stop.setGeometry(QtCore.QRect(70, 120, 91, 41))
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.lbl_thongbao = QtWidgets.QLabel(self.frame)
        self.lbl_thongbao.setGeometry(QtCore.QRect(10, 20, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_thongbao.setFont(font)
        self.lbl_thongbao.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lbl_thongbao.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_thongbao.setStyleSheet("color: rgb(255, 0, 0);\n"
"QLable {\n"
"    text-align: center;\n"
"}")
        self.lbl_thongbao.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_thongbao.setObjectName("lbl_thongbao")
        self.txtSub = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtSub.setGeometry(QtCore.QRect(60, 370, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSub.setFont(font)
        self.txtSub.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtSub.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtSub.setReadOnly(False)
        self.txtSub.setObjectName("txtSub")
        self.txtSub_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtSub_2.setGeometry(QtCore.QRect(60, 410, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSub_2.setFont(font)
        self.txtSub_2.setReadOnly(False)
        self.txtSub_2.setObjectName("txtSub_2")
        self.txtSub_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtSub_3.setGeometry(QtCore.QRect(60, 450, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtSub_3.setFont(font)
        self.txtSub_3.setReadOnly(False)
        self.txtSub_3.setObjectName("txtSub_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_input.setText(_translate("MainWindow", "Input"))
        self.btn_start_stop.setText(_translate("MainWindow", "Start"))
        self.lbl_thongbao.setText(_translate("MainWindow", "TextLabel"))
        self.txtSub.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.txtSub_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.txtSub_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
